services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?Missing MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: perfex
      MYSQL_USER: perfex
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?Missing MYSQL_PASSWORD}
    networks:
      - network
    volumes:
      - ./data:/var/lib/mysql
    command: --authentication-policy=mysql_native_password
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=\"${MYSQL_ROOT_PASSWORD}\" --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 300s
      retries: 60
  crm:
    build:
      context: ./docker
      dockerfile: litespeed.Dockerfile
    restart: unless-stopped
    expose:
      - 80
    #ports:
    #  - 7080:7080
    depends_on:
      mysql:
        condition: service_healthy
    environment:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.perfex.entrypoints=websecure"
      - "traefik.http.routers.perfex.rule=Host(`$DOMAIN`)"
      - "traefik.http.routers.perfex.tls.certresolver=http-challenge"
    networks:
      - network
      - traefik-proxy
    volumes:
      - ./:/var/www/vhosts/localhost/html
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin:latest
    restart: unless-stopped
    expose:
      - "80"
    environment:
      PMA_HOST: mysql
      PMA_ABSOLUTE_URI: https://${DOMAIN:?Missing DOMAIN}/phpmyadmin/
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD?:Missing MYSQL_ROOT_PASSWORD}
      MYSQL_USER: perfex
      MYSQL_PASSWORD: ${MYSQL_PASSWORD?:Missing MYSQL_PASSWORD}
    label:
      - "traefik.enable=true"
      - "traefik.http.routers.matomo-phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.matomo-phpmyadmin.rule=Host(`$DOMAIN`) and Path(`\phpmyadmin`)"
      - "traefik.http.routers.matomo-phpmyadmin.tls.certresolver=http-challenge"
    networks:
      - network
      - traefik-proxy

networks:
  network:
  traefik-proxy:
    name: traefik-proxy
    external: true
